### ISSUE TITLE
Block was found but it was rejected by the daemon

### ISSUE THREAD

**Issue by rlinxy** [blockchaingate/fabcoin#10]
Hi,

I am trying to set up a z-nomp pool for Fab Coin. At the beginning, I got this error
Error: Expected property "1" of type Satoshi, got Number 24950000000000000
After hours research, I made this modified 
 var blockReward = (this.rpcData.miner) * 100000000;
change to
 var blockReward = (this.rpcData.miner);
The blockReward seems to be correct now, it's 2500000000

But later I got this message at the pool side

We thought a block was found but it was rejected by the daemon, share data: {"job":"ce14","ip":"::ffff:169.62.79.66","port":3033,"worker":"1Pr8Y67xWFMKUsKfNdgqtXUVtUGrKHPKVN.noname","height":124296,"difficulty":1000,"shareDiff":"76908.13346099","blockDiff":52614.575953302,"blockDiffActual":52614.575953302,"blockHash":"00000006d12b63a7a8d0836b04fcbbf299e26e4b07c257922b59ad7a38e20474","error":{"unknown":"check coin daemon logs"}}

And below is what in the wallet log:

2018-07-16 15:33:13 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 00000006d12b63a7a8d0836b04fcbbf299e26e4b07c257922b59ad7a38e20474, bad-height, incorrect block height (code 16)
2018-07-16 15:33:13 ERROR: ProcessNewBlock: AcceptBlock FAILED

Seems all the blocks that we might find got rejected.

Any idea what should I do to fix this? Thanks.

**Comment by blockchaingate** [comment]
Hi rlinxy,

Can you paste the raw block data mined by your side?

**Comment by rlinxy** [comment]
I only have the info I pasted previously in the log, isn't it the block hash '00000006d12b63a7a8d0836b04fcbbf299e26e4b07c257922b59ad7a38e20474' that you need? If not, I will go through the code later and find out how to log the raw block data, thanks

**Comment by rlinxy** [comment]
FYI, I am using this 
https://github.com/z-classic/z-nomp
and the node startum pool is 
https://github.com/z-classic/node-stratum-pool
thanks.

**Comment by rlinxy** [comment]
Sorry, but I have no idea how to get the raw block data that I mined. I run the pool again with daemon set 'debug=1', and got one more rejected block. Seems there still no such info in the daemon's log file. Seems something found wrong when checking the Block Header. And I found this in the pool's code:

`    //block header per https://github.com/zcash/zips/blob/master/protocol/protocol.pdf
    this.serializeHeader = function(nTime, nonce){
        var header =  new Buffer(140);
        var position = 0;

        /*
        console.log('nonce:' + nonce);
        console.log('this.rpcData.bits: ' + this.rpcData.bits);
        console.log('nTime: ' + nTime);
        console.log('this.merkleRootReversed: ' + this.merkleRoot);
        console.log('this.prevHashReversed: ' + this.prevHashReversed);
        console.log('this.rpcData.version: ' + this.rpcData.version);
        */

        header.writeUInt32LE(this.rpcData.version, position += 0, 4, 'hex');
        header.write(this.prevHashReversed, position += 4, 32, 'hex');
        header.write(this.merkleRootReversed, position += 32, 32, 'hex');
        header.write('0000000000000000000000000000000000000000000000000000000000000000', position += 32, 32, 'hex'); //hashReserved
        header.write(nTime, position += 32, 4, 'hex');
        header.write(util.reverseBuffer(new Buffer(rpcData.bits, 'hex')).toString('hex'), position += 4, 4, 'hex');
        header.write(nonce, position += 4, 32, 'hex');
        return header;
    };`

Guess I need modify this part.

**Comment by rlinxy** [comment]
@blockchaingate 
Would you please advise? Still have no clue to fix this. We have a community with 3000+ miners, many of them are interested in mining Fab, so I would like to get the pool running ASAP. Thanks a lot!

**Comment by blockchaingate** [comment]
I have no idea without the raw block data and I never read the source code of z-nomp. Maybe the source code below from fabcoin can help.

```
    const int nHeight = pindexPrev->nHeight + 1;
    ......
    // Check block height for blocks after FAB fork.
    if (nHeight >= consensusParams.FABHeight && block.nHeight != (uint32_t)nHeight)
        return state.Invalid(false, REJECT_INVALID, "bad-height", "incorrect block height");
```

**Comment by rlinxy** [comment]
It seems like something wrong with block header. I checked the fab developer reference, link below
http://fabcoins.info/en/developer-reference.html#block-chain
It says the header is 80-byte format. But in znomp I got this:

> nonce:5800000000000000000000009b88000003000000000000000000000000000000
this.rpcData.bits: 1d3c2860
nTime: 8fb3525b
this.merkleRootReversed: fa11feeb90d4c03ba4a7eb7697958b6d9660b816148253bc5bf6bb74c233c0f9
this.prevHashReversed: 0ca79d027cf970c04ec543c4d4e07de2c6c7f9412067f98a222e2e7514000000
this.rpcData.version: 536870912
header-1: 000000200ca79d027cf970c04ec543c4d4e07de2c6c7f9412067f98a222e2e7514000000f9c033c274bbf65bbc53821416b860966d8b959776eba7a43bc0d490ebfe11fa89f90100000000000000000000000000000000000000000000000000000000008fb3525b60283c1d5800000000000000000000009b88000003000000000000000000000000000000

**Comment by rlinxy** [comment]
I still  don't know how to ge 'raw block data' from daemon, any idea?

**Comment by rlinxy** [comment]
OK, below is what I got, on testnet, height 144794

**Comment by rlinxy** [comment]
buf_block(from pool):                    00000020ed58c12d95dfd25c1b7c53d3bd51877fc0a91366fad51b59e481b7c08ec105002cfa050aaf618b4f809a62af6de04f4fa66e0bfaec35ba162e38ab0acb13543500000000000000000000000000000000000000000000000000000000000000000f1f545be94a061f18000000000000000000000045381d001f000000000000000000000000000000fd40050006ad48d61096af9965924214ddf68bdc2a5f0ad10eb86b8d778fa00a823441bad0db7f9de868dc272a162f0b654f0971bc9f142320a54d03e4caa92baed9216e7459b959b9839b6e445fd167aea17d86f7c36e002dc58e8f4a4276603d045a88a7a9bb3fb13ab54713e8353a46a0f6619d9f01704a2936a15a01ed54e3040e0899b0a168cdca42f196c441482cdefc12c2af4cb997b2c8d89e33780798a26edcd356ecabbe91e3032fd4775a9577afae5fe11b2c1d4c7186ae7ef8a42f03b9b678743545a54855976ffd17b1fb19fe6a4003bf6485ee6ade51679fb04c5b0fb5f51ea5f8e1e00892474af01711731c75219baddfed4a2ea5f759ef0882acb63b5e25b9e8cb10c652a0992552bb1e440008f1b3c78ca34f75e03560ee3a0e85dc939e0a82da252fa39d4d4957049af0c28be7345c09a66ab27e833a363767bff69015d1f5c50a43d87b99666972ee9a0240f6713982aaabfecdb74ac9e816ce93bedd379407c2ff65d1b20ac799e6b78d0f473a26ed185ec1f6182a2b33d0bc1a27e8a0f700f0c8abae79ec7d16d9199f9caf3ba55da9cc84879c56742cda4ee995e6ab08eae5ad19472b986f7f9590b8b206ba0c8dd777ba16801995b44a32728e8e8229f093cd48c64b485c9521ab428d255ef341a4226457acea9a167014b9db9327584ec9655760d7981f74d3e8427b355d817864500332a48807d509cf34fab5d3f85de7fe6bcc78f4e40f0e31f1488af32cd169345c552874d29bf016d96f03c5ab4bcd043b2232336599513595096699ede6e580821dc179b75861c669e8a8c2f04a5706131c3ef904264dcfa78281baf9b93664706f35ae951e3f4cc629662c79a0dc240d8c83f46a2f698b535134bbb2d505bd45904f9302cd0d4250947294fee886838ac6301983fba780b308399efdb340ac57ea91efa833524e001e1d60d8d45cddbceaa1592fc5c2a4ded9cc4373058631b2e592cf41094836bdccc97dc2b00a7edc5605f2479ecf921762e7966682ed5507b9fb6135173e27dbef878e0a416b9943a352dedec85dcb6e38bdb00658d9bfe902ef91fe1a71c8533f6ae87df8056ac9145efca2546ac9c7dcbe62bdcfc5cc813f8c8bcffd0f5521098593356b1578d380c12efd291120091dcd5896ec7e875743af22d808fd976820030d1bbb872604fe9b6e3a90b8c91c4e661c35da9a926fdcd6fe2913ff39043f6017853e0f52ac3a9debc69851dccd03154b248e5d68dac9b0b902a0fc1d556960c09e804e2790b3412c90112d169ad40208c64deae1cadadca810350d68ea2166552c6a244439a7897936305a0a113f8bc52fec104cfeff9e1c42b1f37543324cbcee701888fa3f8d92550581272454edcffac640879bb9512ef0da5d21693079cd3f14e05053cd7dd102b5ef7b0189a7a51edd842fd03ef5e01c526b19df670fc04a32a626ad9ee3eaa3490ac7898fbdc9f2bba83b6c6c0d7ebc1db607427e52aa26b13a3961d68df3b7c66f17e34c6d2a0d5158e42eb7750cbefb93096c1dd1b607852d41d9cedab6e01ef20d867fd9c09d346c17fb57439f54bf67c70dfe55aa0678f59006de33fca4060a5ce4621acac45157de27988fe3920ef9d2b8be1816b0d709def98da1f70a773c177b7bea7e4773fa4103f88f68d556c9bf7b779426a2ef95c5d21ed731bd047635208b909245e5eb03d11dbb1e218a6f315863096f132e4da6da65cb00f0ee2acee4e8d0f078bd8f0d7f2da68585b05aaeecc0f9c965dad6138395bb910ef0709bf683ee591b1273580f4c4ce98a50dee1b556b6cd6652e773f3ec053874da7f3d4e4e267aeb180fe5011d0cdb119397ca041cbe2ce6bdfba2111eb8150cf49ae427c46156db129a164eea29ab26d1ebfe0101000000010000000000000000000000000000000000000000000000000000000000000000ffffffff32039a3502005a2d4e4f4d50212068747470733a2f2f6769746875622e636f6d2f6a6f7368756179616275742f7a2d6e6f6d70ffffffff02c0adb694000000001976a91406427764e72f15beb4d6becb35a95f7c9526dc5288ac404b4c00000000001976a91425324fb1029b5aa8c664958b5f96efb1b8f6939488ac00000000

**Comment by rlinxy** [comment]
raw block from daemon:
00000020ed58c12d95dfd25c1b7c53d3bd51877fc0a91366fad51b59e481b7c08ec105003dcd82381e0f7f2a07cff1f4b92e293fb8bdd77cb89e4cbfedc0bf6230d1880a9a35020000000000000000000000000000000000000000000000000000000000c01f545be94a061f200600005a4c56e6e63d20858ba3197a0353d48e000000000000000000000000fd4005006922396043bd80565ad8867c5920b222b03722c003b5c252d706d0fad1edc3f1be77861939c62db4e34e7977687f5b32efc82605313ae6580f58629ca5bf64737489a3e89747af47d65102b92f723e8e5eacb5079abef65bc4e988afea53352f1de80622ea39299c267966479d622cd373b4160323d4066dc704518bfb111031c3b7e1bf05f072e12a765d15a719825f53b61eb426e22de0a529cb41024cf2c230bb2e361b0df906ea0fb3965aacdd223885c38671b5867ea1be3c8416a35b639f3703bdd24202ffcc7ef78d96802e3f6c1141f605cd591ff7d9cee17f6da43a62657cba881b3fdf2d70a996f4af465245d3bde2a0bd82b99c10fa1251db9c7b977b2145bd0486e464e7524d7d12b11816ad22bead07a5e59f6f46321e7a4435bba3fc19ab1b3c3a042d62e35b7970420ff212fb861f153d6b2b25401c7a942f05cbcdd756ba2b5675bfc1619f2a99012265b6628811c37370016f4f70ee8a4a83db0cdd18b52aed7ddfd805db2f9789d0c8af968abbd63ea0132e67c767a66e9378c705a5a55e51b9f4003d303a547f2c2f35a21dddbb9a66214efb0ad640c178f99602af2e2eca87bbf52acc54dc415e487d41d056804c350e75a375632e7d4fd3a80ae3cdff263bba7e8f301f1c75486522bdb52f13c64d51d9fa5be49d3f57a02b667dbcf4d4c7fd13109627114d4b9ace901fb40a04299c1c48702087fc98b165c9d4d3b1ca32f752db44c3efcb1b7276b1cfd7059e42521b5d84d0f4f85c045b06c29f5fec69281d03b529e1709506f9b1e7e032e11e95179a8f718ff0b6acacd9cc9ec0a73d35401f238752f95a974d09c9d211be556d327c3cdcbd86291404870ade2842f3af832a82ce7d991aa830cb6626c744bd17a13923e02cd30b3d23df2505597e3a872d526dad90b1438dde96631871c7f8455ac5fb9fb1010e36f3db27bc759633b78c8a69b83a00e13d7be618120791304a8d74a245218cf4d9a1eea0a797e520060471dbb6ace2417d9145ce4838250223f03adcc40e25f1a14f516d529b8f090c8ff6e46f029c59e0bd0f5057820dd60aefd745612f95e658a93c8e55387f1c1872eea7c8f357e4aad2c9b8a7f305f4f898a12d14a01f7a129688aba30ab44cf64f1dea759496719c26056f8a6ad51cd34185d2a4733170c1d5d2bd22380173b930d883649561abe05f7e7796f823280f04fa13f34c29fba0fe9be110e25b2af047ed2cb638ff

**Comment by rlinxy** [comment]
fixed, confirmed it was the header issue

**Comment by marlinla** [comment]
@rlinxy Could you explain what was wrong with the header? I'm having the same issue.

**Comment by rlinxy** [comment]
Check the source code of fab core, and make sure you have the exactly same definition of the header at your pool side, that should do it.
